### PR TITLE
Export LoRa Module Firmware Version via the AT Command Interface

### PR DESCRIPTION
**Pull request by janakj**
This pull request adds the AT command AT$FVER which can be used to obtain the firmware version from LoRa Module.

### CODE REVIEW

**Comment by hubmartin** [comment]
Thanks for new command. What do you think if the command would rather be called `AT$FWVER`?

**Comment by janakj** [comment]
I tried to keep it consistent with AT$FRESET, but either works for me.

**Comment by janakj** [comment]
Actually, I just realized the F in AT$FRESET stands for factory. AT$FWVER
is fine by me.

**Comment by hubmartin** [comment]
Thanks, merging.

**Pull request merged**
